api/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'api'

urlpatterns = [
  path('', views.Endpoints.as_view(), name='endpoints'),
  path('workshops/<str:slug>/', views.Workshops.as_view(), name='workshop'),
  path('workshops/', views.Workshops.as_view(), name='workshops'),
  path('terms/<str:slug>/', views.Terms.as_view(), name='term'),
  path('terms/', views.Terms.as_view(), name='terms'),
]

app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView
from learner import views as learner_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('library/', RedirectView.as_view(pattern_name='resource:index', permanent=False)),
    path('resource/', include('resource.urls')),
    path('workshops/', include('workshop.urls')),
    path('assessment/', include('assessment.urls')),
    path('learner/', include('learner.urls')),
    path('glossary/', include('glossary.urls')),
    # path('feedback/', include('feedback.urls')), # TODO #480: Reopen the ability for users to login/register (uncomment this line)
    path('installations/', include('install.urls')),
    path('insights/', include('insight.urls')),
    path('shortcuts/', include('backend.urls')),
    # TODO #480: Reopen the ability for users to login/register (uncomment this line)
    # path('register/', learner_views.Register.as_view(), name='register'),
    # path('login/', auth_views.LoginView.as_view(template_name='learner/login.html'), name='login'),
    # path('logout/', auth_views.LogoutView.as_view(template_name='learner/logout.html'), name='logout'),
    # path('reset-password/', auth_views.PasswordResetView.as_view(template_name='learner/password_reset.html'), name='password_reset'),
    path('', include('website.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# handler404 = 'site.views.404'

backend/urls.py
from django.urls import path
# from django.views.generic import RedirectView

from . import views

app_name = 'backend'

urlpatterns = [
  path('', views.IndexRedirect.as_view(), name='index'),
  path('debug/', views.DebugView.as_view()),
  path('term/<str:slug>/', views.TermRedirectView.as_view()),
  path('insight/<str:slug>/', views.InsightRedirectView.as_view()),
  path('install/<str:slug>/', views.InstallRedirectView.as_view()),
  path('workshop/<str:slug>/', views.WorkshopRedirectView.as_view()),
]

learner/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from . import views

app_name = 'learner'

urlpatterns = [
  path('', views.Detail.as_view()),
  path('favorite/', views.favorite, name='favorite'),
  path('instructor-request/', views.InstructorRequests.as_view(), name='instructor_request'),
  path('requests/', views.InstructorRequests.as_view(), name='instructor_requests'),
  path('profile/<str:username>/', views.Detail.as_view(), name='profile'),
  path('activate/<uidb64>/<token>/', views.activate, name='activate'),
]

website/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'website'

urlpatterns = [
  path('', views.Index.as_view(), name='index'),
  # path('<str:slug>/', views.PageView.as_view(), name='page'),
]

website/models.py
from django.db import models



class Snippet(models.Model):
    identifier = models.CharField(max_length=50, unique=True)
    snippet = models.TextField()

    def __str__(self):
        return f'{self.identifier}'

website/views.py
from workshop.models import Workshop
from django.views.generic import ListView


class Index(ListView):
    model = Workshop
    template_name = 'website/index.html'

website/templates/website/admin-viewports.html
<div class="ml-4 text-muted small font-weight-bold">
    <span class="d-inline-block d-sm-none d-xxl-none font-weight-bold">Current viewport:  XS</span>
    <span class="d-none d-sm-inline-block d-md-none d-xxl-none font-weight-bold">Current viewport:SM</span>
    <span class="d-none d-md-inline-block d-lg-none d-xl-none d-xxl-none font-weight-bold">Current viewport: MD</span>
    <span class="d-none d-lg-inline-block d-xl-none d-xxl-none font-weight-bold">Current viewport: LG</span>
    <span class="d-none d-xl-inline-block d-xxl-none font-weight-bold">Current viewport: XL</span>
    <span class="d-none d-xxl-inline-block font-weight-bold">Current viewport: XXL</span>
</div>

website/templates/website/ie_warning.html
{% if 'Trident' in request.META.HTTP_USER_AGENT %}
    <div class="container py-4 zen-hideaway">
    <div class="alert alert-danger" role="alert">
        You are using Internet Explorer. This website does not support Internet Explorer and you will have trouble interacting with parts of it.
    </div>
    </div>
{% endif %}

website/templates/website/navbar-simple.html
<nav class="navbar navbar-dark nav-dark">
  <p class="navbar-brand navbar-toggler border-0 m-0" href="/">
    <!--<img src="/static/website/images/logo.png" width="50" height="50" alt="" loading="lazy" class="mr-2">-->
    <span class="d-none d-md-inline-block"><strong>Curriculum</strong> | Digital Humanities Research Institute</span>
    <span class="d-inline-block d-md-none"><strong>Curriculum</strong> | DH Research Institute</span>
  </p>
  <span class="text-light">
    {% if user.is_authenticated %}
      <a href="{% url 'learner:profile' user.username %}" id="meta-btn">{% if user.first_name and user.last_name %}{{ user.first_name }} {{ user.last_name }}{% else %}{{ user.username }}{% endif %}</a> | <a href="{% url 'logout' %}" id="meta-btn">Log out</a>
    {% else %}
        <a href="{% url 'login' %}{% if not request.get_full_path == '/logout/' %}?next={{ request.get_full_path|urlencode }}{% endif %}" id="meta-btn">Login</a> | <a href="{% url 'register' %}" id="meta-btn">Register</a>
    {% endif %}
  </span>
</nav>