api/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'api'

urlpatterns = [
  path('', views.Endpoints.as_view(), name='endpoints'),
  path('workshops/<str:slug>/', views.Workshops.as_view(), name='workshop'),
  path('workshops/', views.Workshops.as_view(), name='workshops'),
  path('terms/<str:slug>/', views.Terms.as_view(), name='term'),
  path('terms/', views.Terms.as_view(), name='terms'),
]

app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView
from learner import views as learner_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('library/', RedirectView.as_view(pattern_name='resource:index', permanent=False)),
    path('resource/', include('resource.urls')),
    path('workshops/', include('workshop.urls')),
    path('assessment/', include('assessment.urls')),
    path('learner/', include('learner.urls')),
    path('glossary/', include('glossary.urls')),
    # path('feedback/', include('feedback.urls')), # TODO #480: Reopen the ability for users to login/register (uncomment this line)
    path('installations/', include('install.urls')),
    path('insights/', include('insight.urls')),
    path('shortcuts/', include('backend.urls')),
    # TODO #480: Reopen the ability for users to login/register (uncomment this line)
    # path('register/', learner_views.Register.as_view(), name='register'),
    # path('login/', auth_views.LoginView.as_view(template_name='learner/login.html'), name='login'),
    # path('logout/', auth_views.LogoutView.as_view(template_name='learner/logout.html'), name='logout'),
    # path('reset-password/', auth_views.PasswordResetView.as_view(template_name='learner/password_reset.html'), name='password_reset'),
    path('', include('website.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# handler404 = 'site.views.404'

backend/urls.py
from django.urls import path
# from django.views.generic import RedirectView

from . import views

app_name = 'backend'

urlpatterns = [
  path('', views.IndexRedirect.as_view(), name='index'),
  path('debug/', views.DebugView.as_view()),
  path('term/<str:slug>/', views.TermRedirectView.as_view()),
  path('insight/<str:slug>/', views.InsightRedirectView.as_view()),
  path('install/<str:slug>/', views.InstallRedirectView.as_view()),
  path('workshop/<str:slug>/', views.WorkshopRedirectView.as_view()),
]

glossary/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'glossary'

urlpatterns = [
  path('', views.TermList.as_view(), name='index'),
  path('<str:slug>/', views.TermList.as_view(), name='letter'),
  path('term/<str:slug>/', views.TermDetail.as_view(), name='term'),
]

website/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'website'

urlpatterns = [
  path('', views.Index.as_view(), name='index'),
  # path('<str:slug>/', views.PageView.as_view(), name='page'),
]

workshop/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views
from lesson.views import CheckAnswer

app_name = 'workshop'

urlpatterns = [
  path('', views.IndexRedirect.as_view(), name='index'),
  path('<str:slug>/', views.FrontmatterView.as_view(), name='frontmatter'),
  path('<str:slug>/theory-to-practice/', views.PraxisView.as_view(), name='praxis'),
  path('<str:slug>/lessons/', views.LessonView.as_view(), name='lesson'),
  path('<str:slug>/lessons/check-answer/', CheckAnswer.as_view()),
]

website/models.py
from django.db import models



class Snippet(models.Model):
    identifier = models.CharField(max_length=50, unique=True)
    snippet = models.TextField()

    def __str__(self):
        return f'{self.identifier}'

website/views.py
from workshop.models import Workshop
from django.views.generic import ListView


class Index(ListView):
    model = Workshop
    template_name = 'website/index.html'

templates/website/index.html
{% extends 'base.html' %}
{% load markdownify static snippet %}

{% block extra_head_material %}
    <script src="https://unpkg.com/imagesloaded@4/imagesloaded.pkgd.min.js"></script>
{% endblock %}

{% block before_container %}
<section class="jumbotron px-4 py-5" style="border-radius: unset; background-image: url({% static 'website/images/bg-pattern.png' %});">
    <div class="container-xxl">
        <div class="d-flex align-items-center flex-column flex-sm-row">
            <img src="{% static 'website/images/logo.png' %}" class="img-fluid mr-4 mb-2 mb-sm-0" style="max-height:150px;" alt="Graphic that depicts: Digital Humanities Research Institute logotype">
            <div class="text-primary">
                <h1 class="jumbotron-heading mb-3">Further Expanding Digital Humanities Communities of Practice</h1>
                <p style="font-size:1.2rem;">The Digital Humanities Research Institute (DHRI) is an intensive, community-oriented, and foundational approach to learning technical skills in service of humanities teaching and learning. You can read more about the project on <a href="//dhinstitutes.org">our main website</a>.</p>
            </div>
        </div>
    </div>
</section>
{% endblock %}

{% block hero%}
<h1 class="h3 dhri-hero">Digital Humanities Research Institute</h1>
<h1 class="h2 display-4">Curriculum Website</h1>
{% snippet "introduction-website" %}
{% snippet "introduction-curriculum" %}
{% endblock %}

{% block main %}
<section id="workshop-list">
    <div class="container-xxl">
        <h2 class="pt-5">All Workshops</h2>
            <div class="row grid">
            {% for workshop in object_list %}
                <div class="col-lg-6 px-3 py-3">
                <div class="card h-100">
                    {% if workshop.image %}
                        <a href="{% url 'workshop:frontmatter' slug=workshop.slug %}"><img src="{{ workshop.image.url }}" class="card-img-top" alt="{{ workshop.name }}"></a>
                    {% endif %}
                    <div class="card-body">
                        {% if not workshop.image %}
                            <h5 class="card-title m-0 bolder">{{ workshop.name }}</h5>
                        {% endif %}
                        {% if workshop.frontmatter.abstract %}<p class="card-text m-0">{{ workshop.frontmatter.abstract | markdown | safe }}</p>{% endif %}

                        {% if workshop.has_terms %}
                            <div class="mt-2 pt-1 border-top">
                                <strong class="mr-1">Key terms</strong>{% for term in workshop.terms %}
                                <a tabindex="{{ forloop.counter0 }}" class="btn badge btn-light" data-container="body" data-toggle="popover" data-placement="top" data-title="{{ term }}" data-content="{{ term.explication | striptags }} <strong>Click to read more about {{ term }}</strong>" href="{% url 'glossary:term' term.slug %}">{{ term }}</a>
                                {% endfor %}
                            </div>
                        {% endif %}
                    </div>

                    <div class="card-footer text-right">
                        <a href="{% url 'workshop:frontmatter' slug=workshop.slug %}" class="btn btn-primary">Start &raquo;</a>
                    </div>
                </div>
                </div>
            {% endfor %}
        </div>
    </div>
</section>
{% endblock %}

{% block javascript %}
    <script type="application/javascript">
        imagesLoaded( document.querySelector('.grid'), function( instance ) {
            let m = new Masonry( '.grid', {
                percentPosition: true
            });
        });
    </script>
{% endblock %}