api/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'api'

urlpatterns = [
  path('', views.Endpoints.as_view(), name='endpoints'),
  path('workshops/<str:slug>/', views.Workshops.as_view(), name='workshop'),
  path('workshops/', views.Workshops.as_view(), name='workshops'),
  path('terms/<str:slug>/', views.Terms.as_view(), name='term'),
  path('terms/', views.Terms.as_view(), name='terms'),
]

app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView
from learner import views as learner_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('library/', RedirectView.as_view(pattern_name='resource:index', permanent=False)),
    path('resource/', include('resource.urls')),
    path('workshops/', include('workshop.urls')),
    path('assessment/', include('assessment.urls')),
    path('learner/', include('learner.urls')),
    path('glossary/', include('glossary.urls')),
    # path('feedback/', include('feedback.urls')), # TODO #480: Reopen the ability for users to login/register (uncomment this line)
    path('installations/', include('install.urls')),
    path('insights/', include('insight.urls')),
    path('shortcuts/', include('backend.urls')),
    # TODO #480: Reopen the ability for users to login/register (uncomment this line)
    # path('register/', learner_views.Register.as_view(), name='register'),
    # path('login/', auth_views.LoginView.as_view(template_name='learner/login.html'), name='login'),
    # path('logout/', auth_views.LogoutView.as_view(template_name='learner/logout.html'), name='logout'),
    # path('reset-password/', auth_views.PasswordResetView.as_view(template_name='learner/password_reset.html'), name='password_reset'),
    path('', include('website.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# handler404 = 'site.views.404'

backend/urls.py
from django.urls import path
# from django.views.generic import RedirectView

from . import views

app_name = 'backend'

urlpatterns = [
  path('', views.IndexRedirect.as_view(), name='index'),
  path('debug/', views.DebugView.as_view()),
  path('term/<str:slug>/', views.TermRedirectView.as_view()),
  path('insight/<str:slug>/', views.InsightRedirectView.as_view()),
  path('install/<str:slug>/', views.InstallRedirectView.as_view()),
  path('workshop/<str:slug>/', views.WorkshopRedirectView.as_view()),
]

workshop/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views
from lesson.views import CheckAnswer

app_name = 'workshop'

urlpatterns = [
  path('', views.IndexRedirect.as_view(), name='index'),
  path('<str:slug>/', views.FrontmatterView.as_view(), name='frontmatter'),
  path('<str:slug>/theory-to-practice/', views.PraxisView.as_view(), name='praxis'),
  path('<str:slug>/lessons/', views.LessonView.as_view(), name='lesson'),
  path('<str:slug>/lessons/check-answer/', CheckAnswer.as_view()),
]

workshop/views.py
from install.models import Instructions
from django.shortcuts import get_object_or_404, HttpResponseRedirect
from django.core.paginator import Paginator
from workshop.models import Prerequisite, Workshop, Collaboration, Blurb
from lesson.models import Lesson
from learner.models import Profile, Progress
from django.conf import settings
from django.views.generic import View, DetailView
from django.contrib import messages


class IndexRedirect(View):
    def get(self, request):
        return HttpResponseRedirect('/')


def get_progress(workshop=None, profile=None):
    try:
        return Progress.objects.get(profile=profile, workshop=workshop).page
    except:
        return False


class FrontmatterView(DetailView):
    model = Workshop
    template_name = 'workshop/frontmatter.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        self.request.session.set_expiry(0)
        context['has_visited'] = self.has_visited()
        context['user_favorited'] = self.has_favorited()
        context['num_terms'], context['all_terms'] = self.get_all_terms()
        context['frontmatter'] = self.get_object().frontmatter
        context['prerequisites'] = self.get_object().frontmatter.prerequisites
        # context['prerequisites'] = self.get_prerequisites()

        context['learning_objectives'] = [x.label.replace('<p>', '').replace(
            '</p>', '') for x in context['frontmatter'].learning_objectives.all()]
        context['default_user_image'] = settings.MEDIA_URL + Profile.image.field.upload_to + '/' + Profile.image.field.default

        context['all_collaborators'] = Collaboration.objects.filter(
            frontmatter=context['frontmatter']).order_by('contributor__last_name')

        context['current_collaborators'] = context['all_collaborators'].filter(
            current=True).order_by('contributor__last_name')
        context['past_collaborators'] = context['all_collaborators'].filter(
            current=False).order_by('contributor__last_name')
        context['current_authors'] = context['current_collaborators'].filter(
            role='Au').order_by('contributor__last_name')
        context['current_editors'] = context['current_collaborators'].filter(
            role='Ed').order_by('contributor__last_name')
        context['current_reviewers'] = context['current_collaborators'].filter(
            role='Re').order_by('contributor__last_name')
        context['past_authors'] = context['past_collaborators'].filter(
            role='Au').order_by('contributor__last_name')
        context['past_editors'] = context['past_collaborators'].filter(
            role='Ed').order_by('contributor__last_name')
        context['past_reviewers'] = context['past_collaborators'].filter(
            role='Re').order_by('contributor__last_name')

        context['blurbs'] = Blurb.objects.filter(
            workshop=context['workshop']).order_by('user__last_name')

        context['is_frontmatter'] = True

        if self.request.user.is_authenticated:
            context['has_progress'] = get_progress(
                context['workshop'], self.request.user.profile)
        else:
            context['has_progress'] = False

        return context

    def has_visited(self):
        if not self.request.session.get('has_visited', False):
            obj = self.get_object()
            obj.views += 1
            obj.save()
            self.request.session['has_visited'] = True
            return True
        return True

    def has_favorited(self):
        if self.request.user.is_authenticated:
            if self.get_object() in self.request.user.profile.favorites.all():
                return True
        return False

    def get_all_terms(self, sort=True, reverse=False):
        _ = list()
        for lesson in self.get_object().lessons.all():
            _.extend(list(lesson.terms.all()))
        [_.extend(list(lesson.terms.all())) for lesson in self.get_object().lessons.all()]
        if sort: _.sort(key=lambda x: x.slug, reverse=reverse)
        return(len(set(_)), set(_))

    def get_prerequisites(self):
        _ = {
            'required': [],
            'recommended': [],
            'workshops': [],
            'required_installs': [],
            'recommended_installs': [],
            'installs': [],
            'insights': [],
            'external_links': [],
            'cheat_sheets': [],
        }

        for req in self.get_object().frontmatter.prerequisites.all():
            if req.required: _['required'].append(req)
            if req.recommended: _['recommended'].append(req)

            if req.category == Prerequisite.WORKSHOP: _['workshops'].append(req)
            elif req.category == Prerequisite.INSIGHT: _['insights'].append(req)
            elif req.category == Prerequisite.EXTERNAL_LINK: _['external_links'].append(req)
            elif req.category == Prerequisite.CHEATSHEET: _['cheat_sheets'].append(req)

            for software in req.linked_software.all():
                if not req.required and not req.recommended:
                    if not (req, software) in _['installs']:
                        _['installs'].append((req, software))
                elif req.required:
                    if not (req, software) in _['required_installs']:
                        _['required_installs'].append((req, software))
                elif req.recommended:
                    if not (req, software) in _['recommended_installs']:
                        _['recommended_installs'].append((req, software))
        
        return _


class PraxisView(DetailView):
    model = Workshop
    template_name = 'workshop/praxis.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['lessons'] = self.get_object().lessons.all()
        context['praxis'] = self.get_object().praxis
        context['frontmatter'] = self.get_object().frontmatter

        context['is_praxis'] = True
        context['evals'] = self.get_evaluations()
        context['num_evaluations'] = len(context['evals'])

        return context

    def get_evaluations(self):
        _ = []
        for lesson in self.get_object().lessons.order_by('?').all():
            for eval in lesson.evaluations.all():
                if not (len(_) >= 10):
                    _.append(eval)
        return _


class LessonView(DetailView):
    model = Lesson
    template_name = 'lesson/lesson.html'

    def get_object(self):
        workshop = get_object_or_404(Workshop, slug=self.kwargs.get('slug'))

        try:
            self.lessons
        except:
            self.lessons = Lesson.objects.filter(workshop=workshop)

        self.paginator = Paginator(self.lessons, 1)
        self.page_number = self.request.GET.get('page')

        try:
            self.page_number = int(self.page_number)
        except TypeError:
            pass

        if not self.page_number:
            self.page_number = 1

        self.page_obj = self.paginator.get_page(self.page_number)
        self.percentage = round(
            self.page_number / self.paginator.num_pages * 100)

        if self.request.user.is_authenticated:
            if self.request.user.profile:
                if Progress.objects.filter(profile=self.request.user.profile, workshop=workshop).exists():
                    if Progress.objects.filter(profile=self.request.user.profile, workshop=workshop).count() > 1:
                        Progress.objects.filter(
                            profile=self.request.user.profile, workshop=workshop).delete()
                    else:
                        progress_obj = Progress.objects.get(
                            profile=self.request.user.profile, workshop=workshop)
                        if progress_obj.page < self.page_number:
                            progress_obj.page = self.page_number
                            progress_obj.save()
                        elif progress_obj.page == self.page_number:
                            pass  # we are on the same page as the progress..
                        else:
                            messages.success(
                                self.request, f'You have already completed this lesson. <a href="?page={progress_obj.page}">Jump to the last one you completed.</a>')
                else:
                    Progress.objects.create(
                        profile=self.request.user.profile, workshop=workshop, page=self.page_number)

        return self.page_obj.object_list[0]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['workshop'] = get_object_or_404(Workshop, slug=self.kwargs.get('slug'))
        context['paginator'] = self.paginator
        context['page_obj'] = self.page_obj
        context['percentage'] = self.percentage
        context['lessons'] = self.lessons
        return context

templates/workshop/praxis.html
{% extends 'base.html' %}
{% load markdownify static snippet %}


{% block extra_head_material %}
  <link rel="stylesheet" href="{% static 'workshop/css/praxis.css' %}">
<script>
  Object.prototype.allFalse = function() {
      for (var i in this) {
          if (this[i] === true) return false;
      }
      return true;
  }

  function disable_all_elements(elemList) {
    for (x in elemList) {
      target_elem = elemList[x]
      if (typeof target_elem == 'object') {
        target_elem.classList.add('disabled');
        target_elem.disabled = true;
      }
    }
  }

  function enable_all_elements(elemList) {
    for (x in elemList) {
      target_elem = elemList[x]
      if (typeof target_elem == 'object') {
        target_elem.classList.remove('disabled');
        target_elem.disabled = false;
      }
    }
  }

  function submit_answer_praxis(e) {
    answers = {};

    let questionID = e.target.dataset.qid;
    let alertDiv = document.querySelector(`#alert-${questionID}`);
    let elems = [...e.target.elements]

    elems = elems.filter(e=>{return typeof(e) === 'object' &&
    e.dataset &&
    e.dataset.answer_id});

    elems.forEach(e => {
      answers[e.dataset.answer_id] = e.checked;
    });

    if (answers.allFalse()) {
      alertDiv.innerText = "At least one response is true. Choose one!"
      alertDiv.classList.remove('d-none');
      return false;
    }

    // disable all buttons and get all the answers
    disable_all_elements(elems);

    fetch('/workshops/{{ workshop.slug }}/lessons/check-answer/', {
        method: "POST",
        credentials: "same-origin",
        headers: {
            "X-CSRFToken": getCookie("csrftoken"),
            "Accept": "application/json",
            "Content-Type": "application/json",
            "Question": questionID,
            "Answers": JSON.stringify(answers)
        },
        body: ''
    }).then(function(response) { return response.json();
    }).then(function(data) {
        if (data.error == null) {
          if (data.all_correct == true) {
            alertDiv.classList.add('d-none');
            e.target.parentElement.parentElement.style = 'background-color: rgba(0, 170, 100, 0.1) !important;'
            e.target.getElementsByTagName('button')[0].classList.remove('btn-primary')
            e.target.getElementsByTagName('button')[0].classList.add('btn-success')
            e.target.getElementsByTagName('button')[0].classList.add('disabled')
            e.target.getElementsByTagName('button')[0].innerHTML = 'Correct answer!'
            return true;
          } else {
            //console.log('set to try again!')
            e.target.parentElement.parentElement.style = 'background-color: #db53343b !important;'
            alertDiv.innerText = "Unfortunately, that was not the correct answer. Try again!"
            alertDiv.classList.remove('d-none');
            enable_all_elements(elems);
            return false;
          }
        } else {
          console.error(data.error);
        }
    }).catch(function(ex) {
        console.error(ex);
    });

  }
</script>
<style>
  .eval-cards .card-body {
            max-height: 400px;
            overflow: scroll;
          }
          .eval-cards .card-body::-webkit-scrollbar {
            /* -webkit-appearance: none; */
            width: 5px;
          }
          
          .eval-cards .card-body::-webkit-scrollbar-thumb {
            border-radius: 5px;
            background-color: rgba(0,0,0,.5);
            -webkit-box-shadow: 0 0 1px rgba(255,255,255,.5);
          }
</style>
{% endblock %}


{% block secondary_menu %}
    {% include 'workshop/fragments/secondary-menu.html' %}
{% endblock %}


{% block hero %}
<div class="px-3 py-3 pt-md-5 pb-md-4 mx-auto text-left">
  <div id="hero">
    {% include 'workshop/fragments/praxis/hero.html' %}
    <div class="lead mt-4" data-replace-internal-links="true">
      {{ praxis.intro | as_string | markdown | safe }}
    </div>
  </div><!-- /hero -->
</div>
{% endblock %}


{% block admin_edit %}
  <a class="text-decoration-none dropdown-item admin-link-django" target="_blank" href="{% url 'admin:index' %}">Django admin</a>
  <a class="text-decoration-none dropdown-item admin-link-edit" target="_blank" href="{% url 'admin:workshop_praxis_change' praxis.id  %}">Edit theory-to-practice page</a>
  <a class="text-decoration-none dropdown-item admin-link-github" target="_blank" href="https://www.github.com/{{ workshop.parent_repo }}/blob/{{ workshop.parent_branch }}/theory-to-practice.md">See on GitHub</a>
{% endblock %}


{% block main %}

{% if num_evaluations %}
  <section class="bg-extra-super-light shadow">
    <div class="container-xxl px-3 py-3 px-md-5 py-md-5">
      <h3 class="mt-4 pb-3 mb-4 border-bottom">Review your knowledge: {{ num_evaluations }} questions from the lessons</h3>
      <div class="row grid">
        {% for evaluation in evals %}
          {% for question in evaluation.questions.all|slice:"1" %}
            <div class="col-md-6 px-4 py-4 eval-cards">
              <div class="card h-100">
                <div class="card-body small">            
                  {% include 'lesson/fragments/evaluation-question.html' %}
                </div>
                <div class="card-footer small">
                  Revisit lesson <a href="{% url 'workshop:lesson' slug=evaluation.lesson.workshop.slug %}?page={{ evaluation.lesson.order }}">{{ evaluation.lesson }}</a> to learn more.
                </div>
              </div>
            </div>
          {% endfor %}
        {% endfor %}
      </div>
    </div>
  </section>
{% endif %}
<section class="bg-extra-super-light-green shadow-sm">
  <div class="container-xxl px-3 py-3 px-md-5 py-md-5">
  <h3>Deepen your knowledge</h3>
  
  <div class="row">
    {% if praxis.discussion_questions.count %}
      <div class="col-12 mt-5">
        <h4>Discussion Questions</h4>
        <hr />
        <ul>
        {% for question in praxis.discussion_questions.all %}
          <div class="lead mt-4">
            <li>{{ question.label | markdown | safe }}</li>
          </div>
        {% endfor %}
        </ul>
      </div>
    {% endif %}

    {% if praxis.next_steps.count %}
      <div class="col-12 mt-5">
        <h4>Next Steps</h4>
        <hr />
        {% for step in praxis.next_steps.all %}
          <div class="lead mt-4">
            {{ step.label | markdown | safe }}
          </div>  
        {% endfor %}  
      </div>  
    {% endif %}  

    {% if praxis.tutorials.count %}
    <div class="col-12 mt-5">
      <h4>Tutorials</h4>
      <div>{% snippet 'introduction-tutorials' %}</div>
      <hr />
      <div class="lead mt-4">
        {% for tutorial in praxis.tutorials.all %}
          <div class="p-2 my-3 rounded-lg linked-comment">
            {% if tutorial.url %}
              <p class="font-weight-bold"><a href="{{ tutorial.url }}" class="stretched-link">{% if tutorial.title %}{{ tutorial.title | as_string | markdown | safe | striptags }}{% else %}Untitled{% endif %}</a></p>
            {% else %}
              <p class="font-weight-bold">Untitled</p>
            {% endif %}
            {% if tutorial.annotation %}
              <p class="small">{{ tutorial.annotation | stringformat:"s" | markdown | safe }}</p>
            {% endif %}
          </div>
        {% endfor %}
      </div>
    </div>
    {% endif %}

    {% if praxis.further_readings.count %}
    <div class="col-12 mt-5">
      <h3>Further Readings</h3>
      <div class="font-weight-bold">{% snippet 'introduction-resources' %}</div>
      <hr />
      <div class="lead mt-4">
        {% for reading in praxis.further_readings.all %}
          <div class="p-2 my-3 rounded-lg linked-comment">
            {% if reading.url %}
              <p class="font-weight-bold"><a href="{{ reading.url }}" class="stretched-link">{% if reading.title %}{{ reading.title | as_string | markdown | safe | striptags }}{% else %}Untitled{% endif %}</a></p>
            {% else %}
              <p class="font-weight-bold">Untitled</p>
            {% endif %}
            {% if reading.annotation %}
              <p class="small">{{ reading.annotation | stringformat:"s" | markdown | safe }}</p>
            {% endif %}
          </div>
        {% endfor %}
      </div>
    </div>
    {% endif %}

    {% if praxis.further_projects.count %}
    <div class="col-12 mt-5">
      <h3>Projects or Challenges to Try</h3>
      <div class="font-weight-bold">{% snippet 'introduction-further-projects' %}</div>
      <hr />
      <div class="lead mt-4">
        {% for project in praxis.further_projects.all %}
          <div class="p-2 my-3 rounded-lg linked-comment">
            {% if project.url %}
                <p class="font-weight-bold"><a href="{{ project.url }}" class="stretched-link">{% if project.title %}{{ project.title | as_string | markdown | safe | striptags }}{% else %}Untitled{% endif %}</a></p>
              {% else %}
                <!--<p class="font-weight-bold">Untitled</p>-->
              {% endif %}
              {% if project.annotation %}
                <p class="small">{{ project.annotation | stringformat:"s" | markdown | safe }}</p>
              {% endif %}
          </div>
        {% endfor %}
      </div>
    </div>
  {% endif %}

</div>


{% endblock %}


{% block javascript %}
  <script src="{% static 'workshop/js/navbar.js' %}" crossorigin="anonymous"></script>
  <script>
    var forms = document.getElementsByClassName('submit-answer');
    for (let form of forms) {
        form.addEventListener('submit', function(evt) {
          evt.preventDefault();
          submit_answer_praxis(evt);
          evt.preventDefault();
        });
    }
  </script>
{% endblock %}