api/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'api'

urlpatterns = [
  path('', views.Endpoints.as_view(), name='endpoints'),
  path('workshops/<str:slug>/', views.Workshops.as_view(), name='workshop'),
  path('workshops/', views.Workshops.as_view(), name='workshops'),
  path('terms/<str:slug>/', views.Terms.as_view(), name='term'),
  path('terms/', views.Terms.as_view(), name='terms'),
]

app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView
from learner import views as learner_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('library/', RedirectView.as_view(pattern_name='resource:index', permanent=False)),
    path('resource/', include('resource.urls')),
    path('workshops/', include('workshop.urls')),
    path('assessment/', include('assessment.urls')),
    path('learner/', include('learner.urls')),
    path('glossary/', include('glossary.urls')),
    # path('feedback/', include('feedback.urls')), # TODO #480: Reopen the ability for users to login/register (uncomment this line)
    path('installations/', include('install.urls')),
    path('insights/', include('insight.urls')),
    path('shortcuts/', include('backend.urls')),
    # TODO #480: Reopen the ability for users to login/register (uncomment this line)
    # path('register/', learner_views.Register.as_view(), name='register'),
    # path('login/', auth_views.LoginView.as_view(template_name='learner/login.html'), name='login'),
    # path('logout/', auth_views.LogoutView.as_view(template_name='learner/logout.html'), name='logout'),
    # path('reset-password/', auth_views.PasswordResetView.as_view(template_name='learner/password_reset.html'), name='password_reset'),
    path('', include('website.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# handler404 = 'site.views.404'

backend/urls.py
from django.urls import path
# from django.views.generic import RedirectView

from . import views

app_name = 'backend'

urlpatterns = [
  path('', views.IndexRedirect.as_view(), name='index'),
  path('debug/', views.DebugView.as_view()),
  path('term/<str:slug>/', views.TermRedirectView.as_view()),
  path('insight/<str:slug>/', views.InsightRedirectView.as_view()),
  path('install/<str:slug>/', views.InstallRedirectView.as_view()),
  path('workshop/<str:slug>/', views.WorkshopRedirectView.as_view()),
]

insight/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from .views import Index, InsightDetail

app_name = 'insight'

urlpatterns = [
  path('', Index.as_view(), name='index'),
  path('<str:slug>/', InsightDetail.as_view(), name='insight'),
]

insight/models.py
from django.db import models
from django.utils.text import slugify
from install.models import Software
from backend.dhri_utils import dhri_slugify


class Insight(models.Model):
    title = models.CharField(max_length=80, unique=True)
    slug = models.CharField(max_length=200, blank=True, unique=True)
    software = models.ManyToManyField(Software)
    text = models.TextField(blank=True, null=True)
    image = models.ImageField(
        upload_to='insight_headers/', default='insight_headers/default.png')
    image_alt = models.TextField(blank=True, null=True)

    def save(self, *args, **kwargs):
        self.slug = dhri_slugify(self.title)
        super(Insight, self).save()

    def __str__(self):
        return f'{self.title}'

    class Meta:
        ordering = ['title']


class Section(models.Model):
    insight = models.ForeignKey(
        Insight, on_delete=models.CASCADE, related_name='sections')
    order = models.PositiveSmallIntegerField()
    title = models.CharField(max_length=80)
    text = models.TextField(blank=True, null=True)

    def __str__(self):
        return f'{self.title}'

    class Meta:
        ordering = ['order']


class OperatingSystemSpecificSection(models.Model):
    section = models.ForeignKey(
        Section, on_delete=models.CASCADE, related_name='os_specific_sections')
    operating_system = models.CharField(max_length=80)
    text = models.TextField(blank=True, null=True)

    def __str__(self):
        return f'OS Specific Instructions for section {self.section.title}'

insight/views.py
from django.shortcuts import render, HttpResponse, get_object_or_404
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from .models import Insight


class Index(ListView):
    model = Insight


class InsightDetail(DetailView):
    model = Insight

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['object_list'] = self.model.objects.all()
        return context

templates/insight/insight_detail.html
{% extends 'base.html' %}

{% block admin_edit %}
  <a class="text-decoration-none dropdown-item admin-link-edit" target="_blank" href="{% url 'admin:insight_insight_change' insight.id %}">Edit</a>
{% endblock %}

{% block hero %}
<div class="pt-5 border-bottom">
    <img src="{{ insight.image.url }}" class="img-fluid mb-3" style="min-width:100%;" />
    <h2 class="py-2">{{ insight.title }}</h2>
    {% if insight.text %}
        <div class="lead"><p>{{ insight.text | safe }}</p></div>
    {% endif %}
</div>
{% endblock %}

{% block main %}
<section id="insight-sections">
    <div class="container-xxl">
        {% for section in insight.sections.all %}
            {% if section.title %}
                <h3 class="mt-5 mb-2">{{ section.title | safe }}</h3>
            {% endif %}
            <div class="lead" data-replace-internal-links="true">
                {{ section.text | safe }}
            </div>
            {% for os_section in section.os_specific_sections.all %}
                <h4>{{ os_section.operating_system }}</h4>
                {{ os_section.text | safe }}
            {% endfor %}
        {% endfor %}
    </div>
</section>
{% endblock %}

templates/insight/insight_list.html
{% extends 'base.html' %}

{% block main %}
<div class="container-xxl">
    <div class="row">
        {% for insight in object_list.all %}
            <div class="col-lg-6 px-3 py-3">
                <div class="card text-center h-100">
                    <div class="card-body">
                        <img src="https://cdn.searchenginejournal.com/wp-content/uploads/2020/06/how-to-use-python-to-monitor-and-measure-website-performance-5ed76ef838ff3-760x400.png" class="card-img-top" alt="{{ insight.title }}">
                        <h5 class="card-title pt-3">{{ insight.title }}</h5>
                        <p class="card-text">{{ insight.text | safe }}</p>
                        <a class="btn btn-sm btn-primary stretched-link" href="{% url 'insight:insight' insight.slug %}">Start</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}